### ISSUE TITLE
Bug? renaming environments in latex

### ISSUE THREAD

**Issue by bkasel** [quarto-ext/latex-environment#10]
Dear developpers,

I am unsure if I hit a bug or if this works the way it should and I am using it in the wrong way.

I would like to have a `.column` div in a `.qmd` file be converted to a `minipage` environment in latex and I thought this should work using this extension by using:

```yaml
environments:
  - column: minipage
```

However this does not produce any envs in latex.

Weirdly,

```yaml
environments:
  - minipage: column
```
produces a `column` in latex

I found a work-around by adding 2 classes to my div `:::{.column .minipage arguments="0.3\textwidth"}`

**Comment by cderv** [comment]
I am missing a lot of context here because no .qmd source code shared, meaning no idea of format you are using, if you are in a project, and all your OS & versions context. I'll do an answer to the best I can with what I have. 

This is working for me.

````markdown
---
title: LaTeX Environment
format: latex
filters:
   - latex-environment
environments:
  column: minipage
---

::: {.column}
Will this be a minipage ?
:::
````

This produce a minipage 
````latex
\begin{document}
\maketitle
\begin{minipage}
Will this be a minipage ?
\end{minipage}
\end{document}
````

Though about `.column`, note this is a special environment already, for example in beamer format (https://quarto.org/docs/presentations/beamer.html#multiple-columns) so not a good idea to use this one for your divs class. 

So maybe there is something else, or maybe you need to update.

**Comment by bkasel** [comment]
Hello,

Sorry for not being clearer.

Your MWE works for me as well. I am working on a Win10/11 PC with quarto 1.3.450

I managed to reproduce the problem in the following way:
Creating a new book project
```bash
quarto create
```
Add to `_quarto.yaml`:
```yaml
     keep-tex: true
    filters:
      - latex-environment
    environments:
      - column: minipage
```

Add the following paragraph to any `qmd` file
```markdown
::: {.column}
will this be a minipage?
:::
```
then render:
```bash
quarto render
````

The produced tex file has no minipage.

When I switch the order in the `_quarto.yaml` file:
```yaml
- minipage: column
```
I get a `column` env in the latex file

**Comment by cderv** [comment]
What format are you rendering too ?  

Would you be able to try pre-release ? https://quarto.org/docs/download/prerelease.html

**Comment by cderv** [comment]
Also check the syntax in README. 
This is not correct: 
````yaml
filters:
  - latex-environment
environments:
  - column: minipage
 ````

You need named list for `environments`
````yaml
environments:
  column: minipage
````

Using `-` is not the same.

**Comment by bkasel** [comment]
Thank you!

I used the `-` because I was trying to get a "mixed" list to work, like:
```yaml
environments:
  - column: minipage
  - center
```
which works in the weird way I was describing while this way immediately throws an error
```yaml
    environments:
      column: minipage
      center
```
Now with the following syntax it works as expected:
```yaml
    environments:
      column: minipage
      center: center #needs to be specified
```
